### ISSUE TITLE
problem with gzip

### ISSUE THREAD

**Issue by dsebban** [takipi/heroku-buildpack-takipi#1]
getting this after following instructions  :

remote: -----> Fetching set buildpack https://github.com/takipi/heroku-buildpack-takipi.git... done
remote: -----> Takipi app detected
remote: -----> Installing Takipi...
remote: gzip: stdin: not in gzip format
remote: tar: Child returned status 1
remote: tar: Error is not recoverable: exiting now
remote: mv: cannot stat ‘/tmp/build_8b95d31375769d8a532086afdc4f55c9/takipi’: No such file or directory
remote:  done
remote: 
remote: -----> Discovering process types
remote:        Procfile declares types -> web
remote:

**Comment by juherr** [comment]
Same issue here.

The reason is the needed file has "Access Denied": https://s3.amazonaws.com/app-takipi-com/deploy/linux/takipi-latest-heroku-1lde.tar.gz

**Comment by chook** [comment]
This is embarrassing. Sorry guys and thanks for the heads up! 
Apparently our recent AWS key rotation mechanism needed some more tweaks. 

File is reachable now and the buildpack is working again. Thanks for notifying!
